import type { Metadata } from 'next';
import SearchPanel from '@/components/SearchPanel';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'AI Domain Name Generator for .al Domains | AIDotAL',
  description: 'An AI domain name generator that starts with a business brief, not a keyword. Get scored .al domain candidates with meaning, recall, and risk analysis.',
};

export default function AiGeneratorPage() {
  return (
    <div className={styles.page}>
      <div className="section-max">
        <div className={styles.header}>
          <p className="kicker">AI DOMAIN NAME GENERATOR</p>
          <h1>AI Domain Name Generator</h1>
          <p className={styles.sub}>Most domain search tools are keyword boxes. This one starts with a business brief and returns a reasoned shortlist — not just a list of available strings.</p>
        </div>

        <div className={styles.mainSearch}>
          <SearchPanel />
        </div>

        <div className={styles.sections}>
          <section className={styles.section}>
            <h2>Why AI improves domain discovery</h2>
            <p>A keyword box tells you what&apos;s available. An AI scoring system tells you what&apos;s worth having. The difference matters when you&apos;re building something that needs to be remembered, typed, and talked about.</p>
            <p>Traditional domain search optimizes for availability. AI-assisted search optimizes for fit — matching the name to the product, the audience, and the market. That means surfacing names you wouldn&apos;t have typed, and explaining why each one is or isn&apos;t a good candidate.</p>
          </section>

          <section className={styles.section}>
            <h2>How the scoring model works</h2>
            <div className={styles.dimGrid}>
              {[
                { label: 'Meaning fit (25 pts)', desc: 'Does the name connect naturally to the product, the outcome, and the audience? A name that requires explanation every time someone hears it has low meaning fit.' },
                { label: 'Recall (20 pts)', desc: 'Can someone say the name in a meeting, not see it for a week, and type it correctly? Short, distinct names with no ambiguity score highest.' },
                { label: 'Pronunciation (15 pts)', desc: 'Can someone say it correctly after seeing it once? Names that create ambiguity when spoken — "is it /sɪg/ or /saɪg/?" — lose points here.' },
                { label: 'Spelling risk (15 pts)', desc: 'Will someone type what they heard? Double letters, unusual combinations, and near-homophones all introduce spelling risk. Lower risk = higher score.' },
                { label: 'Market fit (10 pts)', desc: 'Does the name feel appropriate for the category, language, and audience? A name that sounds great in English may not carry the same weight in global markets.' },
                { label: 'Availability (verified)', desc: 'Availability is checked at the time of search. A final live check is always run before registration. Availability is not guaranteed until registration completes.' },
              ].map(d => (
                <div key={d.label} className={styles.dimCard}>
                  <h3 className={styles.dimLabel}>{d.label}</h3>
                  <p className={styles.dimDesc}>{d.desc}</p>
                </div>
              ))}
            </div>
          </section>

          <section className={styles.section}>
            <h2>Example: capit.al — a domain hack</h2>
            <div className={styles.exampleCard}>
              <div className={styles.exampleTop}>
                <span className={styles.exampleDomain}>capit<span className={styles.exAl}>.al</span></span>
                <span className={styles.exampleScore}>88</span>
              </div>
              <p className={styles.exampleDesc}>
                <strong>What it is:</strong> &ldquo;capit.al&rdquo; is a domain hack — the .al extension completes the word &ldquo;capital.&rdquo; The name does double duty: it&apos;s a memorable address and a brand statement. Domain hacks are powerful when they work because the extension reinforces the meaning rather than competing with it.
              </p>
              <p className={styles.exampleDesc}>
                <strong>Why it scores high:</strong> The meaning fit is strong for finance, investment, and institutional products. Recall is high because &ldquo;capital&rdquo; is a familiar English word. Pronunciation is unambiguous. The only watch-out is category specificity — &ldquo;capital&rdquo; carries a strong finance connotation that may not serve every audience.
              </p>
            </div>
          </section>

          <section className={styles.section}>
            <h2>Not just any AI — explainable scoring</h2>
            <p>The scores and explanations are generated by Claude (Anthropic&apos;s AI model) using a structured system prompt that enforces the scoring rubric. The rationale, &ldquo;why it works,&rdquo; and watch-out sections are not marketing copy — they&apos;re the model&apos;s actual reasoning for each candidate.</p>
            <p>You can disagree with the score. The point is to give you a starting position with a reason, not to replace your judgment. Domain naming involves tradeoffs that only you can weigh — audience expectations, competitive landscape, trademark situation, personal preference. The AI surfaces the measurable dimensions; you make the call.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
