import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import styles from './page.module.css';

type Props = { params: Promise<{ doc: string }> };

const DOCS: Record<string, { title: string; content: () => React.ReactNode }> = {
  terms: {
    title: 'Terms of Service',
    content: () => (
      <>
        <section>
          <h2>Acceptance</h2>
          <p>By using AIDotAL, you agree to these terms. If you do not agree, do not use the service. These terms apply to all services provided by AIDotAL, including domain discovery, registration workflow, and managed DNS.</p>
        </section>
        <section>
          <h2>Service description</h2>
          <p>AIDotAL provides AI-assisted domain name discovery, managed .al domain registration, and authoritative DNS management. The service is provided as described on this site at the time of purchase. We reserve the right to modify features with notice.</p>
        </section>
        <section>
          <h2>Account</h2>
          <p>You are responsible for maintaining the security of your account credentials. You must notify us immediately of any unauthorized access. We are not liable for losses resulting from unauthorized account access where the breach is attributable to you.</p>
        </section>
        <section>
          <h2>Registrations</h2>
          <p>Domain registrations are submitted to the .al registry on your behalf. Registration success depends on availability at the time of submission and registry acceptance. We do not guarantee registration and will refund if registration fails.</p>
        </section>
        <section>
          <h2>DNS</h2>
          <p>Managed DNS is provided on a best-effort basis. We are not liable for losses caused by DNS propagation delays, record misconfiguration, or service interruptions outside our control.</p>
        </section>
        <section>
          <h2>Payment</h2>
          <p>Fees are charged annually. Payment is processed at time of registration or renewal. Prices are shown pre-tax; applicable taxes are added at checkout.</p>
        </section>
        <section>
          <h2>Cancellation</h2>
          <p>You may cancel your account at any time. Domain registrations run to their expiry date. DNS management ends when the domain expires or you transfer to external nameservers.</p>
        </section>
        <section>
          <h2>Liability</h2>
          <p>To the maximum extent permitted by law, AIDotAL is not liable for indirect, incidental, or consequential damages arising from use of the service. Our liability for direct damages is limited to the amount paid in the 12 months preceding the claim.</p>
        </section>
        <section>
          <h2>Governing law</h2>
          <p>These terms are governed by the laws of the jurisdiction in which AIDotAL is incorporated. Disputes will be resolved through binding arbitration unless otherwise required by law.</p>
        </section>
      </>
    ),
  },
  privacy: {
    title: 'Privacy Policy',
    content: () => (
      <>
        <section>
          <h2>Data collected</h2>
          <p>We collect information you provide (name, email, payment information, domain preferences), information generated by your use of the service (search queries, registration history, DNS configuration), and technical information (IP address, browser type, device).</p>
        </section>
        <section>
          <h2>How used</h2>
          <p>We use collected data to provide the service, process registrations, manage DNS, send account notifications, and improve the product. We do not sell personal data to third parties.</p>
        </section>
        <section>
          <h2>Third parties</h2>
          <p>We share data with the .al registry for domain registration (required), payment processors for billing (required), and infrastructure providers operating under data processing agreements. We do not share data with advertisers.</p>
        </section>
        <section>
          <h2>Retention</h2>
          <p>Account data is retained while your account is active and for a period after closure as required by law. Domain registration data is retained for the duration of registration plus the period required by registry policy.</p>
        </section>
        <section>
          <h2>Rights</h2>
          <p>Depending on your jurisdiction, you may have rights to access, correct, delete, or port your personal data. Contact us to exercise these rights. We will respond within 30 days.</p>
        </section>
        <section>
          <h2>Cookies</h2>
          <p>We use essential cookies for session management and authentication. We do not use advertising or tracking cookies.</p>
        </section>
        <section>
          <h2>Contact</h2>
          <p>Privacy questions can be directed to the contact form on this site.</p>
        </section>
      </>
    ),
  },
  refunds: {
    title: 'Refund Policy',
    content: () => (
      <>
        <section>
          <h2>When refunds apply</h2>
          <p>Refunds apply when: (1) a registration fails because the domain was unavailable at submission time; (2) a registration fails due to registry rejection for eligibility reasons beyond your control; (3) a technical error on our side prevents the registration from completing.</p>
        </section>
        <section>
          <h2>When they don&apos;t</h2>
          <p>Refunds do not apply to: successfully registered domains (the domain is registered and cannot be returned to the registry); registrations that fail due to inaccurate contact information you provided; or change-of-mind after a registration is submitted.</p>
        </section>
        <section>
          <h2>Process</h2>
          <p>To request a refund, contact us through the support channel. Include your account email, the domain name, and the reason for the request. We will review and respond within 5 business days.</p>
        </section>
        <section>
          <h2>Timing</h2>
          <p>Approved refunds are processed within 10 business days and returned to the original payment method. Processing time on your card or bank may add additional days.</p>
        </section>
      </>
    ),
  },
  'registration-policy': {
    title: 'Registration Policy',
    content: () => (
      <>
        <section>
          <h2>Eligibility</h2>
          <p>Most .al domain registrations are open to individuals and organizations worldwide, subject to accurate registrant information. Some categories or names may have additional eligibility requirements imposed by the .al registry. We surface these requirements before submission.</p>
        </section>
        <section>
          <h2>Contact requirements</h2>
          <p>You must provide accurate registrant contact information: legal name (or organization name), postal address, phone number, and email address. Inaccurate contact information may cause registration rejection or future suspension.</p>
        </section>
        <section>
          <h2>Manual review</h2>
          <p>Some registrations may be subject to manual review by the .al registry. Registration timelines can vary. We will notify you of the status through your account.</p>
        </section>
        <section>
          <h2>Registry policies</h2>
          <p>The .al registry (AKEP) maintains its own registration policies that supersede ours. By registering a .al domain through us, you agree to comply with registry policies. We are not responsible for decisions made by the registry.</p>
        </section>
        <section>
          <h2>Failure handling</h2>
          <p>If a registration fails, we will notify you by email, explain the reason where the registry has provided one, and refund the registration fee. We will not retry a failed registration without your explicit instruction.</p>
        </section>
      </>
    ),
  },
};

export function generateStaticParams() {
  return Object.keys(DOCS).map(doc => ({ doc }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { doc } = await params;
  const d = DOCS[doc];
  if (!d) return { title: 'Document Not Found' };
  return { title: `${d.title} | AIDotAL`, description: `AIDotAL ${d.title}` };
}

export default async function LegalPage({ params }: Props) {
  const { doc } = await params;
  const d = DOCS[doc];
  if (!d) notFound();

  return (
    <div className={styles.page}>
      <div className="section-max">
        <div className={styles.draftBanner} role="alert">
          <span aria-hidden="true">&#9888;</span> DRAFT — This document requires legal review before publication.
        </div>
        <div className={styles.header}>
          <p className="kicker">LEGAL</p>
          <h1>{d.title}</h1>
        </div>
        <div className={styles.content}>{d.content()}</div>
      </div>
    </div>
  );
}
